### PR TITLE
Combined Editor Widget configuration and loading with Filter Editor dijit

### PR DESCRIPTION
**Pull request by kgonzago**
Used the edit widget configuration experience to highlight the filter editor dijit.

### CODE REVIEW

**Comment by kgonzago** [comment]
@dhagens I merged Mike's changes l into your dev branch. Can you confirm all is good? Thanks.

**Comment by dhagens** [comment]
@kgonzago @MikeMillerGIS  Looks like there are a few issues.  The scroll bar is cutting off the TemplatePicker when I bring it up.  Also seeing some undefined values when selecting a template and hovering over the map.  Also odd that there is a large scrollbar on the right when the TemplatePicker is only using half the space.

**Comment by dhagens** [comment]
I believe the scroll bar cutting off the TemplatePicker was a caching issue.  Tried again in chrome and IE after deleting cache and that seems to be fine.  The other two issues are shown below.

filtereditor
filtereditorundefined

**Comment by dhagens** [comment]
@kgonzago @MikeMillerGIS I reviewed the code, and maybe I'm missing the big picture here, but don't see why we would add the editor code to the Widget.js in the FilterEditor widget.  It not only causes some issues with sizing, but seems to add confusion since the only editor that is being displayed is the FilterEditor.  Why introduce all of that other code in here for no reason?  Seems simpler to keep it the way it was to show how easy it is to use the FilterEditor dijit within a widget?  Am I missing something here?

**Comment by MikeMillerGIS** [comment]
My reasoning is that we need to create a widget for users to use the filtereditor dijit.  I would like to see this in core where I can use it as part of ArcGIS Online.  

I think we can look at enhancing the core editor widget to allow the users to select the filter editor instead of the editor.  By default, the editor widget would use the editor dijit.  We would add a check box to the editor widget to let the user select the filtereditor.  

Can we make this happen?  If so, we should actually add this to the 1.3 version of the editor widget.  I did this code yesterday so I could easily show off the filtereditor as the widget that exposed it was hard coded to a service and did not use the configuration experience of WAB to define the layers.

**Comment by dhagens** [comment]
Makes sense. Do we still need this FilterEditor widget that displays the functionality of the dijit or just use the Editor widget to allow the user to select between the two?

**Pull request merged**
